name: Build Curated Digest (manual)

on:
  workflow_dispatch:
    inputs:
      days:
        description: 'Number of days of firehose to seed'
        required: false
        default: '7'

permissions:
  contents: write

jobs:
  build-digest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run build_digest.py
        env:
          DAYS: ${{ github.event.inputs.days }}
        run: |
          python scripts/build_digest.py
          ls -la curated

      - name: Commit & push curated draft
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add curated/*.md
          git commit -m "docs(curated): seed monthly digest"
          git push
