name: Vendor Watch — Fortinet

on:
  schedule:
    - cron: '35 10 * * *'   # 10:35 UTC daily (~6:35 AM US/Eastern)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-fortinet-page:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install feedparser pyyaml requests beautifulsoup4

      - name: Build Fortinet watch page
        env:
          PAGE_TITLE: "Vendor Watch — Fortinet"
          # Any-match keywords (case-insensitive) — removed CVE-20
          KEYWORDS: "Fortinet, FortiOS, FortiGate, FortiWeb, FortiProxy, FortiManager, FortiAnalyzer, FortiNAC, FortiSwitch, FortiAP, FortiEDR, FortiClient, FortiSASE"
          # Feed names that should always be included (case-insensitive substring match)
          SOURCE_MATCH: "Fortinet, FortiGuard"
          # Extra feeds to include in addition to feeds.yaml (comma-separated URLs)
          EXTRA_FEEDS: "https://www.reddit.com/r/fortinet/top/.rss?t=day", "https://feeds.fortinet.com/fortinet/blogs"
          # Where to write the page
          OUTPUT_PATH: "curated/vendors/fortinet.md"
          # How many articles to fetch OG metadata for (performance knob)
          OG_SCRAPE_LIMIT: "40"
        run: |
          python scripts/build_vendor_page.py

      - name: Commit & push page
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add curated/vendors/fortinet.md
          git commit -m "docs(vendor): update Fortinet watch page" || echo "Nothing to commit"
          git push
